# Generated by Django 3.1.3 on 2020-12-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201214_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='usertype',
            field=models.CharField(choices=[('t', 'Teacher'), ('a', 'Administrator'), ('s', 'Student')], help_text='Choose a User type', max_length=1, null=True),
        ),
    ]
