# Generated by Django 3.1.3 on 2020-12-27 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityrecord',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.userprofile'),
        ),
    ]
