# Generated by Django 3.1.3 on 2020-12-27 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_auto_20201227_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityrecord',
            name='current_certification',
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, null=True)),
                ('current_certification', models.CharField(choices=[('v', 'Vocational'), ('d', 'Designated'), ('c', 'Conditional'), ('e', 'Semi Professional'), ('b', 'Basic'), ('s', 'Standard'), ('p', 'Professional')], help_text='Choose a certification', max_length=1)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='activityrecord',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.teacher'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
