# Generated by Django 3.1.3 on 2020-12-27 18:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201227_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityrecord',
            name='summary',
            field=models.CharField(help_text='Summarize what you have learned from the combined activities and how you plan to apply this learning to your classroom', max_length=3000, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
