# Generated by Django 3.1.3 on 2020-12-28 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20201227_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='CEUs',
            new_name='ceu',
        ),
    ]
