# Generated by Django 3.1.3 on 2020-12-29 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20201229_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='currentcertification',
            new_name='current_certification',
        ),
    ]
