# Generated by Django 3.1.3 on 2020-12-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_teacher_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profile_pic',
            field=models.ImageField(blank=True, default='blank-profile.jpg', null=True, upload_to=''),
        ),
    ]
