# Generated by Django 3.1.3 on 2020-12-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20201230_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='current_certification',
            field=models.CharField(blank=True, choices=[('v', 'Vocational'), ('d', 'Designated'), ('c', 'Conditional'), ('e', 'Semi Professional'), ('b', 'Basic'), ('s', 'Standard'), ('p', 'Professional')], help_text='Choose a certification', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
