# Generated by Django 3.1.3 on 2021-01-05 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20201230_1510'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActivityDescription',
            new_name='ActivityCategory',
        ),
        migrations.RenameField(
            model_name='activitycategory',
            old_name='description',
            new_name='detail',
        ),
    ]
