# Generated by Django 3.1.3 on 2021-01-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20210105_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitycategory',
            name='typicalCEUvalue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
