# Generated by Django 3.1.3 on 2021-01-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_activitycategory_typicalceuvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycategory',
            name='typicalCEUvalue',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
