# Generated by Django 3.1.3 on 2021-01-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20210105_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycategory',
            name='typicalCEUvalue',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
